### ISSUE TITLE
error: relation "metadata._typeorm_migrations" does not exist

### ISSUE THREAD

**Issue by nickgupta33** [twentyhq/twenty#12454]
Very new to 20 CRM on the self hosted version. I installed the latest version of the application using docker and I have been receiving this error since the first time I installed it. Not sure why this issue is coming up can someone help me? 

<img width="1201" alt="Image" src="https://github.com/user-attachments/assets/f0fa8b77-ae1a-41e8-90a0-77c9536f94d4" />

**Comment by FelixMalfait** [comment]
Sorry this has been fixed here: https://github.com/twentyhq/twenty/pull/12398
But not tagged yet. We will release the next major version on Thursday or Friday

**Comment by FelixMalfait** [comment]
In the meantime you could edit the code or directly go in your DB and create an empty _typeorm_migrations table in the metadata schema, that would fix the issue

**Comment by nickgupta33** [comment]
I did add a table to the DB however its still throwing errors. I guessed the migrations were pending, so I ran the migrate and upgrade commands on twenty-server-1, but to no avail. Let's wait for the new version, as I think it must be handled well in the code. 

`server-1  | [Nest] 56  - 06/05/2025, 9:43:07 AM     LOG [CopyTypeormMigrationsCommand] Starting to copy _typeorm_migrations from metadata to core
db-1      | 2025-06-05 09:43:07.708 UTC [460] ERROR:  column "id" does not exist at character 53
db-1      | 2025-06-05 09:43:07.708 UTC [460] STATEMENT:  SELECT * FROM metadata._typeorm_migrations ORDER BY id ASC
server-1  | query failed: SELECT * FROM metadata._typeorm_migrations ORDER BY id ASC
server-1  | error: error: column "id" does not exist
server-1  | [Nest] 56  - 06/05/2025, 9:43:07 AM   ERROR [CopyTypeormMigrationsCommand] Failed to copy migrations: column "id" does not exist
server-1  | [Nest] 56  - 06/05/2025, 9:43:07 AM   ERROR [CopyTypeormMigrationsCommand] undefined
server-1  | [Nest] 56  - 06/05/2025, 9:43:07 AM   ERROR [DatabaseMigrationService] Error running database migrations:
server-1  | [Nest] 56  - 06/05/2025, 9:43:07 AM   ERROR [DatabaseMigrationService] QueryFailedError: column "id" does not exist
server-1  | [Nest] 56  - 06/05/2025, 9:43:07 AM   ERROR [UpgradeCommand] Command failed
server-1  | [Nest] 56  - 06/05/2025, 9:43:07 AM   ERROR [UpgradeCommand] undefined
server-1  | [Nest] 56  - 06/05/2025, 9:43:07 AM     LOG [UpgradeCommand] Command completed!
server-1  | [Nest] 56  - 06/05/2025, 9:43:07 AM   ERROR [QueryFailedError] column "id" does not exist`

**Comment by pavsap** [comment]
Experiencing similar issue with missing relation "metadata._typeorm_migrations"

```
[Nest] 112  - 06/10/2025, 11:50:32 AM     LOG [DatabaseConfigDriver] [INIT] Loading initial config variables from database
[Nest] 112  - 06/10/2025, 11:50:32 AM     LOG [DatabaseConfigDriver] [INIT] Config variables loaded: 0 values found in DB, 61 falling to env vars/defaults
[Nest] 112  - 06/10/2025, 11:50:32 AM     LOG [DatabaseMigrationService] Found 0 active or suspended workspaces that are below version 0.53.0

[Nest] 112  - 06/10/2025, 11:50:32 AM     LOG [DatabaseMigrationService] Running global database migrations
[Nest] 112  - 06/10/2025, 11:50:32 AM     LOG [DatabaseMigrationService] Running metadata datasource migrations...
[Nest] 112  - 06/10/2025, 11:50:32 AM     LOG [CopyTypeormMigrationsCommand] Starting to copy _typeorm_migrations from metadata to core
query failed: SELECT * FROM metadata._typeorm_migrations ORDER BY id ASC
error: error: relation "metadata._typeorm_migrations" does not exist
[Nest] 112  - 06/10/2025, 11:50:32 AM   ERROR [CopyTypeormMigrationsCommand] Failed to copy migrations: relation "metadata._typeorm_migrations" does not exist
[Nest] 112  - 06/10/2025, 11:50:32 AM   ERROR [CopyTypeormMigrationsCommand] undefined
[Nest] 112  - 06/10/2025, 11:50:32 AM   ERROR [DatabaseMigrationService] Error running database migrations:
[Nest] 112  - 06/10/2025, 11:50:32 AM   ERROR [DatabaseMigrationService] QueryFailedError: relation "metadata._typeorm_migrations" does not exist
[Nest] 112  - 06/10/2025, 11:50:32 AM   ERROR [UpgradeCommand] Command failed
[Nest] 112  - 06/10/2025, 11:50:32 AM   ERROR [UpgradeCommand] undefined
[Nest] 112  - 06/10/2025, 11:50:32 AM     LOG [UpgradeCommand] Command completed!
[Nest] 112  - 06/10/2025, 11:50:32 AM   ERROR [QueryFailedError] relation "metadata._typeorm_migrations" does not exist
Exception Captured
  undefined
  [
    QueryFailedError: relation "metadata._typeorm_migrations" does not exist
        at PostgresQueryRunner.query (/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async CopyTypeormMigrationsCommand.runMigrationCommand (/app/packages/twenty-server/dist/src/database/commands/upgrade-version-command/0-53/0-53-copy-typeorm-migrations.command.js:38:40)
        at async DatabaseMigrationService.runMigrations (/app/packages/twenty-server/dist/src/database/commands/upgrade-version-command/upgrade.command.js:100:13)
        at async UpgradeCommand.runMigrationCommand (/app/packages/twenty-server/dist/src/database/commands/upgrade-version-command/upgrade.command.js:157:9)
        at async UpgradeCommand.run (/app/packages/twenty-server/dist/src/database/commands/command-runners/migration.command-runner.js:43:13)
        at async Command.<anonymous> (/app/node_modules/nest-commander/src/command-runner.service.js:162:24)
        at async Command.parseAsync (/app/node_modules/commander/lib/command.js:936:5)
        at async CommandRunnerService.run (/app/node_modules/nest-commander/src/command-runner.service.js:202:9)
        at async CommandFactory.runApplication (/app/node_modules/nest-commander/src/command.factory.js:37:9) {
      query: 'SELECT * FROM metadata._typeorm_migrations ORDER BY id ASC',
      parameters: undefined,
      driverError: error: relation "metadata._typeorm_migrations" does not exist
          at /app/node_modules/pg/lib/client.js:526:17
          at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
          at async PostgresQueryRunner.query (/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:184:25)
          at async CopyTypeormMigrationsCommand.runMigrationCommand (/app/packages/twenty-server/dist/src/database/commands/upgrade-version-command/0-53/0-53-copy-typeorm-migrations.command.js:38:40)
          at async DatabaseMigrationService.runMigrations (/app/packages/twenty-server/dist/src/database/commands/upgrade-version-command/upgrade.command.js:100:13)
          at async UpgradeCommand.runMigrationCommand (/app/packages/twenty-server/dist/src/database/commands/upgrade-version-command/upgrade.command.js:157:9)
          at async UpgradeCommand.run (/app/packages/twenty-server/dist/src/database/commands/command-runners/migration.command-runner.js:43:13)
          at async Command.<anonymous> (/app/node_modules/nest-commander/src/command-runner.service.js:162:24)
          at async Command.parseAsync (/app/node_modules/commander/lib/command.js:936:5)
          at async CommandRunnerService.run (/app/node_modules/nest-commander/src/command-runner.service.js:202:9) {
        length: 127,
        severity: 'ERROR',
        code: '42P01',
        detail: undefined,
        hint: undefined,
        position: '15',
        internalPosition: undefined,
        internalQuery: undefined,
        where: undefined,
        schema: undefined,
        table: undefined,
        column: undefined,
        dataType: undefined,
        constraint: undefined,
        file: 'parse_relation.c',
        line: '1428',
        routine: 'parserOpenTable'
      },
      length: 127,
      severity: 'ERROR',
      code: '42P01',
      detail: undefined,
      hint: undefined,
      position: '15',
      internalPosition: undefined,
      internalQuery: undefined,
      where: undefined,
      schema: undefined,
      table: undefined,
      column: undefined,
      dataType: undefined,
      constraint: undefined,
      file: 'parse_relation.c',
      line: '1428',
      routine: 'parserOpenTable'
    }
  ]
[Nest] 112  - 06/10/2025, 11:50:32 AM     LOG [PgPoolSharedService] pg Pool for key "localhost|5432|postgres||no-ssl" has been closed. Remaining pools: 0
```

**Comment by nickgupta33** [comment]
I checked the updated file, @FelixMalfait can we confirm if this is added to the image or will this take time, or maybe we are doing something wrong?? I am at v0.54.6 for now.

**Comment by FelixMalfait** [comment]
Hey, it's fixed on v0.55+ ; you can upgrade to v0.55.5
