### ISSUE TITLE
Some users are facing workspace in a different language that the one selected

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#12865]
## Bug Description

I've just investigated a user issue that was facing a dutch-translated data model while having selected "en" in their workspace preference.

It's likely that the metadata returned to the front is cached and served in the wrong language.

## Technical details

Investigated the cache and the worksppce had 4 languages in cached graphql objectMetadataOperation

## To reproduce

Play with workspace preference language (Settings > Experience) and see if we can reproduce the issue

**Comment by StephanieJoly4** [comment]
confirming this has been reported by new customers today, this one in Thai so this is hard for them to work (English speaking)

**Comment by StephanieJoly4** [comment]
Another customer reported this issue this morning - let me know if you want his workspace id to help debug @charlesBochet

**Comment by charlesBochet** [comment]
Fixed in v1.0.4 and v1.1 later this week :)

**Comment by prastoin** [comment]
Hello there, reopening this issue as two cloud production user faced the same issue 🤔 
https://discord.com/channels/1130383047699738754/1397141022303191040
https://discord.com/channels/1130383047699738754/1397514597031870525

**Comment by ananda-bhatta** [comment]
## Still experiencing this issue in latest version

  **Environment:**
  - Twenty CRM version: `twentycrm/twenty:latest` (self-hosted)
  - Browser: Edge
  - Deployment: Kubernetes/Docker

  **Problem:**
  Despite the fix in v1.0.4/v1.1, I'm still seeing German text in table headers when my workspace locale is set to `en`:

  - Workspace navigation shows "Unternehmen" instead of "Companies"
  - Table headers show German: "Domainname", "Erstellt von", "Kontoinhalber"
  - Getting "Uncompiled message detected" console errors

  **What I've tried:**
  1. ✅ Verified workspace locale is set to `en`
  2. ✅ Cleared browser cache completely
  5. ✅ Tested in incognito mode

  **API verification:**
  GET /rest/workspaceMembers shows locale: "en"
  GET /rest/metadata/fields shows all English labels
  GET /rest/metadata/objects shows all English labels

**Comment by charlesBochet** [comment]
Fixed by https://github.com/twentyhq/twenty/pull/13710
