### ISSUE TITLE
Workflow cannot be triggered for all records

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#14192]
**Scenario:**
1. Log in
2. Create new workflow where trigger is selected record (rest of workflow isn't important)
3. Open record table of object chosen in step 2
4. Click main checkbox located in the header of record table
5. Check command menu

**Actual:** Workflow trigger disappears from command menu

https://github.com/user-attachments/assets/8c9acba5-5958-44c0-b8de-88221390b698

**Expected:** Workflow trigger is visible in command menu

**Note:** If all records are selected one by one, then workflow trigger appears in command menu, only disappears when main checkbox is checked by user

**Comment by Bonapara** [comment]
Fixed! (in lab)

**Comment by mydalat** [comment]
> Fixed! (in lab)

When will the new update fix this bug? I’m currently on the latest version v1.8.2, but I still don’t see this issue being addressed.

**Comment by mydalat** [comment]
@Bonapara

**Comment by Bonapara** [comment]
I didn’t get it right. Reopening for a fix

**Comment by thomtrp** [comment]
@FelixMalfait keeping that one opened as discussed so we implement the feature after April release

**Comment by FelixMalfait** [comment]
@thomtrp sorry couldn't resist 😬
