### ISSUE TITLE
[Opportunities] - Urgent Bug - “Export View” Download Missing Columns

### ISSUE THREAD

**Issue by fulsan** [twentyhq/twenty#15851]
## Bug Description

When clicking **“Export View”** in **Opportunities → "By Stage" or "All Opportunities"**, the downloaded file includes just a few columns, for example, these **4 columns** when exporting the "By Stage" view (ID, Name, Company ID, Owner ID). Previously the export correctly generated the full set of **~20 expected columns** based on out data model. This severely impacts reporting workflows.

Additionally, a **custom view** created inside Opportunities is now **completely broken** the data no longer displays correctly or aligns with the expected fields. 

Both issues appeared in recent days.

## Expected behavior

When clicking "Export View" inside Opportunities, all the expected columns should be included in the download.

When opening a custom view inside Opportunities, the full data should be visible correctly.

**Comment by BOHEUS** [comment]
Similar export issue (#15575) to yours has been fixed recently, are you self-hosted or cloud? Also, please separate those problems to different issues

**Comment by fulsan** [comment]
@BOHEUS Thanks for the quick response!

We are using the cloud version and we are still seeing the issue today. It looks like the fix mentioned in issue #15575 has not reached the cloud version yet or it does not cover this scenario. In our case the export now contains fewer columns than before.

Ok! I'll separate the issue in 2 and will reference both here.

Thanks again!

**Comment by BOHEUS** [comment]
@fulsan please create an issue for custom view problem, let's leave this issue open for CSV export problem

CC: @StephanieJoly4 @lucasbordeau

**Comment by StephanieJoly4** [comment]
cc @charlesBochet  as I believe you're the one who worked on it last week.

Thank you @BOHEUS for the ping and @fulsan for reporting the issue

**Comment by fulsan** [comment]
Thanks @StephanieJoly4 ! Please let us know if any news about this Export View issue, it is critical for our current data pipelines within the CRM :)

I also created a separate issue for the Custom View:

[Opportunities] - Custom View Not Displaying Data Correctly #15863

**Comment by fulsan** [comment]
Hi @etiennejouan, thanks for reviewing this issue.

Since this affects the cloud version and impacts our data pipelines, could you share whether there's a resolution ETA?

Thanks!

**Comment by charlesBochet** [comment]
Hi @fulsan, since it seems quite impactful, we will priortize a fix before EOW

**Comment by etiennejouan** [comment]
Hi @fulsan, please, could you contact me on Discord (@etiennejouan - or by email : etienne[at]twenty.com) ? Don't manage to reproduce your issue, I would need to investigate on your workspace data model.

**Comment by charlesBochet** [comment]
As we can't reproduce, I'm closing, let's follow up on discord. As you are a cloud user, you can also reach out through the Support button on the app. We will take a deep look at your workspace and make sure it's fixed
