### ISSUE TITLE
email synchronization is experiencing issues

### ISSUE THREAD

**Issue by shivambhateja** [twentyhq/twenty#16073]
Using the open-source version, I would appreciate your guidance on all possible solutions to ensure my email sync operates effectively.
The email synchronization is experiencing issues, no email contacts or companies synced, while the calendar synchronization is functioning smoothly. What steps can I take to resolve the email sync problem?

**Comment by neo773** [comment]
Please include details like what provider you're using, server worker logs etc.

**Comment by shivambhateja** [comment]
Here is the people page showcasing the contacts generated via integrating Google Calendar: https://cln.sh/bVQdH8Z0
Here are the settings I have made in the admin settings: https://cln.sh/cwDnw66j
Mail settings page: https://cln.sh/GDx3frNZ

Could you please tell me where to find the server worker logs? And then I'll send you those logs as well.

**Comment by neo773** [comment]
Could you also add a screenshot for the email accounts page where it shows the sync status of the account?
And as for getting the logs, it depends on where you hosted it. If you are using Docker, check the Docker logs.

**Comment by shivambhateja** [comment]
https://cln.sh/72Z0zFP9
https://cln.sh/Pq46zrWq

Is there any possibility that I can come on a call and show you the system?
In case you need access to the server, that's also okay. I installed this via Docker.

**Comment by neo773** [comment]
It looks like it's stuck on importing. I think this might be related to the bug we recently fixed I would advise you to wait for the next tagged release, version 1.12. It should be out by the end of this week.

**Comment by shivambhateja** [comment]
https://cln.sh/5YQXHLy4

But when I tried on the Cloud version, and not on my own self-hosted version, it is working perfectly fine.

Could you please help me how I can send the emails from the CRM itself?
I am not able to set up the SMTP OR I am not able to verify my domain because I am not able to receive any kind of verification link. There is some mistake on the SMTP server side. 

https://cln.sh/5qJr3cBp
https://cln.sh/7Tqhb7HK

**Comment by neo773** [comment]
Hi there, the reason the cloud version worked fine is because the Docker image is behind Clod, but we released the new version on Docker Hub. That should resolve your issue. Let me know if you face any other issues.

**Comment by shivambhateja** [comment]
Hi @neo773 

I updated my self-hosted Docker setup to the latest tagged release (v1.12 as advised) and redeployed the containers, but the issue still persists.

Current status:
Email accounts section still shows “Sync failed” 
No email contacts or companies are syncing
Calendar sync continues to work correctly

I’ve attached a screenshot of the current Email Accounts sync status from my self-hosted instance for reference.

<img width="982" height="414" alt="Image" src="https://github.com/user-attachments/assets/c7198083-d2c4-417c-8e4c-1628d231ce14" />

<img width="996" height="416" alt="Image" src="https://github.com/user-attachments/assets/4986eea8-e5be-4613-82f4-8f6cee7be511" />

Steps already done:
Pulled latest Docker images
Rebuilt containers
Restarted worker + backend services
Reconnected Google accounts

However, the email sync remains non-functional.

Could you please guide on:
Where I should look specifically for relevant worker logs to debug this further?
Any additional flags / config values / migrations required post-v1.12 upgrade for email sync to work?
Whether this issue is related to any remaining known bugs still open for self-hosted installations?

Thankyou

**Comment by neo773** [comment]
@shivambhateja 
What cloud hosting provider are you using? If it's a bare metal VPS, you'll have to SSH into it and use the docker CLI to get the worker logs.

**Comment by shivambhateja** [comment]
@neo773 

<img width="831" height="328" alt="Image" src="https://github.com/user-attachments/assets/7d3882dd-dc89-4c85-ae99-38ca298062d7" />
<img width="228" height="93" alt="Image" src="https://github.com/user-attachments/assets/30ae58ff-17d9-48e9-b254-af486f8eddc8" />

Thanks for the help and prompt responses. Much appreciated.
The sync is working fine now. I was able to figure out using the logs that there was a Google People API access missing.
 
But there is another concern for accounts who are getting synced. The total number of people synced done is 8889. As soon as I clicked on the export view, the sync stopped. On all the accounts, it is showing as synced in a green bottom. But I guess as soon as I clicked on the export, not even a single email/people was synced.

Is this just a coincidence or the syncing stopped by terminating some internal sync process?
Is there any option that I can resume the sync and it can re-check whether the sync is in place?
Or is there any option I can find till what date the emails are synced?

**Comment by shivambhateja** [comment]
@neo773 could you please help me with an update on this?

**Comment by alexszilagyi** [comment]
In my case I had to add the DNS server, like the following to the server and worker services:

```
    dns:
      - 8.8.8.8
      - 8.8.4.4
```
