### ISSUE TITLE
List group by views are showing duplicated sections and records

### ISSUE THREAD

**Issue by StephanieJoly4** [twentyhq/twenty#16276]
## Bug Description
https://github.com/twentyhq/private-issues/issues/384

this is a front end issue cc @lucasbordeau  and @Devessier

**Comment by Devessier** [comment]
Assigning the issue to @lucasbordeau as he's recently worked on the table. Thank you. Feel free to tell me if you need help.

**Comment by charlesBochet** [comment]
Fixed in v1.13, closing

**Comment by StephanieJoly4** [comment]
@charlesBochet this is not fixed as still happening on my workspace (which looks bad for demos). Can someone please have a look?

**Comment by ijreilly** [comment]
I'll have a look today !

**Comment by ijreilly** [comment]
@StephanieJoly4 I was able to fix the view manually, I suspect the view data had been corrupted in a way which, I think/hope has been fixed now - so cannot be corrupted again. Please ping me directly if it comes back !

**Comment by StephanieJoly4** [comment]
thank you @ijreilly !
