### ISSUE TITLE
[Bug] Gui adds 1 year to the Due Date for Tasks

### ISSUE THREAD

**Issue by fendle** [twentyhq/twenty#16854]
## Bug Description

The Task has the Due Date "2025-12-28T09:58:27.000Z"

<img width="480" height="64" alt="Image" src="https://github.com/user-attachments/assets/ef0cf6ff-e407-4602-9329-1b681fd6daa9" />

Gui shows for the Due Date "2026-12-28

<img width="466" height="85" alt="Image" src="https://github.com/user-attachments/assets/b0784722-1a10-47ee-b214-a79ad5a92a58" />

But pressing on the Date shows again the correct date:

<img width="444" height="538" alt="Image" src="https://github.com/user-attachments/assets/1749bea3-538e-4c55-91e5-e6899a3d3d67" />

**Comment by vasu1303** [comment]
Hi @fendle I tried but wasn't able to reproduce this issue. Can you share a video or exact steps to when this is coming?

**Comment by fendle** [comment]
You can see already on the task overview. The strange thing is, it's only for the dates 2025-12-28 and 2025-12-30 the increase, for the other dates it's fine: 

<img width="306" height="1843" alt="Image" src="https://github.com/user-attachments/assets/45854112-0b13-4efd-91f6-3aded56e37b4" />  

I changed now manually one of my other entries to this date: 2025-12-28 and I got 2026-12-28.

You could do the same and would see it. I am on the Version 1.14

**Comment by BOHEUS** [comment]
@fendle do you still have said issue?

CC: @lucasbordeau

**Comment by lucasbordeau** [comment]
It should be solved now.

**Comment by BOHEUS** [comment]
@fendle could you please confirm if your issue is fixed?

**Comment by fendle** [comment]
issue is still there:
In the single task overview: 

<img width="601" height="165" alt="Image" src="https://github.com/user-attachments/assets/123a65c3-abda-4622-ae4c-c86e6038d7af" />

When I press on it (here is the correct date shown):

<img width="541" height="630" alt="Image" src="https://github.com/user-attachments/assets/4b6bf507-69e8-4111-bd8e-1140891e5576" />

**Comment by lucasbordeau** [comment]
Could you please update to v1.17 and test again, this bug has been fixed recently : https://hub.docker.com/r/twentycrm/twenty/tags?name=v1.17.0

**Comment by fendle** [comment]
<img width="660" height="949" alt="Image" src="https://github.com/user-attachments/assets/2c93d798-30bd-4530-a92d-c6561282c244" /> 
Still there for me

**Comment by lucasbordeau** [comment]
Could you give us your computer's timezone, and the user settings timezone (both can be different) ? So we can try to reproduce locally

**Comment by BOHEUS** [comment]
@fendle do you still have this problem?

**Comment by lucasbordeau** [comment]
I'm closing this issue, please re-open if you can provide more details so we can help you if you still have this problem.
