### ISSUE TITLE
Object metadata item "favoriteFolder" cannot be found in an array of 31 elements

### ISSUE THREAD

**Issue by dascwf** [twentyhq/twenty#9289]
## Bug Description

upgrade to [0.35.2] ( since a month ago version ) , start with:
docker compose -f /home/git/app/crm/twenty/docker-compose.yml up -d

The site show:

Unexpected Application Error!
Object metadata item "favoriteFolder" cannot be found in an array of 31 elements
Error: Object metadata item "favoriteFolder" cannot be found in an array of 31 elements
    at Rt (https://crm.net/assets/index-DVy5hbdC.js:2376:18687)
    at rd (https://crm.net/assets/index-DVy5hbdC.js:2488:4279)
    at dye (https://crm.net/assets/index-DVy5hbdC.js:7023:3490)
    at I2t (https://crm.net/assets/index-DVy5hbdC.js:7023:4034)
    at dDr (https://crm.net/assets/index-DVy5hbdC.js:7033:777)
    at $ue (https://crm.net/assets/index-DVy5hbdC.js:46:17111)
    at G$e (https://crm.net/assets/index-DVy5hbdC.js:48:44390)
    at H$e (https://crm.net/assets/index-DVy5hbdC.js:48:40078)
    at j6t (https://crm.net/assets/index-DVy5hbdC.js:48:40001)
    at iP (https://crm.net/assets/index-DVy5hbdC.js:48:39849)

**Before the upgrade, it had never happened before.**

**Comment by kirilkirkov** [comment]
@dascwf 
I have made upgrade from v0.32.2 to v0.35.2. So I had the same error as you have and i fixed it with:

```
yarn database:migrate:prod
yarn command:prod upgrade-0.35
```

If you use docker compose , login to the **twentycrm/twenty** image, eg. **sudo docker exec -it IMAGE-ID sh**
then run the commands above and this error with be fixed.

**Comment by FelixMalfait** [comment]
Yes @kirilkirkov you need to sync the workspace metadata, favoriteFolder is a new object that was introduced. That command will run the `workspace:sync-metadata` command under the hood which will fix you workspace.

In Q1 @ehconitin will work on an admin panel to manage this more efficiently from a UI :)

**Comment by dascwf** [comment]
@kirilkirkov 

These commands are very useful, and I have fixed them! I originally thought it would take a long time to repair, so I am extremely grateful to you!

I wish the official team could also have your level of responsiveness and repair speed.

**Comment by StefanoMarchesi** [comment]
I have the same problem but running the migration and the upgrade didn't fix it, I have 2 errors in the update output:
[Nest] 3867  - 01/16/2025, 4:52:15 PM   ERROR [ViewGroupNoValueBackfillCommand] Error backfilling view group no value for workspace e38b5b3f-8b09-424b-b78f-f552ef391e5c: EntityPropertyNotFoundError: Property "viewGroups" was not found in "view". Make sure your query is correct.
[Nest] 3867  - 01/16/2025, 4:52:15 PM   ERROR [ViewGroupNoValueBackfillCommand] undefined

and

[Nest] 3867  - 01/16/2025, 4:52:15 PM   ERROR [WorkspaceSyncMetadataService] Sync of standard objects failed with:
[Nest] 3867  - 01/16/2025, 4:52:15 PM   ERROR [WorkspaceSyncMetadataService] Error: Field email1 not found in originalObjectMetadata

Can you help me?

**Comment by FelixMalfait** [comment]
Hey @StefanoMarchesi did you run `npx nx run twenty-server:command workspace:sync-metadata -f`? The error message seems to indicate that you didn't. If you ran the upgrade command it shouldn't run the sync metadata underneath so it's strange that you still have the error
